call IMAP('==', '&=', 'tex')
call IMAP('EEq',"\<Esc>a\\begin{equation*}\<CR><++>\<CR>\\end{equation*}<++>",'tex')
call IMAP('EEA',"\\begin{align}\<CR><++>\<CR>\\label{<++>}\<CR>\\end{align}<++>",'tex')
call IMAP('EEa',"\\begin{align*}\<CR><++>\<CR>\\end{align*}<++>",'tex')
call IMAP('EES',"\\begin{equation}\<CR>\\begin{split}\<CR><++>\<CR>\\label{<++>}\<CR>\\end{split}\<CR>\\end{equation}<++>",'tex')
call IMAP('EEs',"\\begin{equation*}\<CR>\\begin{split}\<CR><++>\<CR>\\end{split}\<CR>\\end{equation*}<++>",'tex')
call IMAP('`e','\epsilon','tex')
call IMAP('`o','\omega','tex')
call IMAP('`O','\Omega','tex')
call IMAP('`P','\Pi','tex')
call IMAP('ETT','\times 10^{<++>}<++>','tex')
call IMAP('ETt','10^{<++>}<++>','tex')
call IMAP('^@','^2','tex')
call IMAP('UNI',"\\left ( \\frac{ \\text{<++>} } { \\text {<++>} } \\right)<++>",'tex')
call IMAP('`+','\dagger','tex')
call IMAP('`f','\phi','tex')
call IMAP('EV','\langle <++> \rangle <++>','tex')
"call IMAP('\ll',\ll,'tex')
